
theme: tuur29/pages-themes-cayman
title: CVPR 2023 Workshop on Event-based Vision
github: 
  is_project_page: false

twitter:
  username: guillermogb
  
# About/contact
author:
  name:       Guillermo Gallego
  url:        http://www.guillermogallego.es

colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
